apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: x-minikube-postgres
spec:
  # Specify that this PVC wants to be bind with PV from
  # the "manual" StorageClass.
  #
  # Repeating the same point in pv.yaml
  #
  # Despite called `storageClassName`, k8s doesn't actually need you
  # to explicitly create this `StorageClass` resource beforehand.
  #
  # You just need to make sure that PV that need to be bind with this PVC
  # also specify "manual" on its `storageClassName` configuration in order
  # to be bind accordingly
  #
  # Docs link about this: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  #
  # Here's slightly highlighted section about this:
  #
  # A claim can request a particular class by specifying the name of a
  # StorageClass using the attribute "storageClassName". Only PVs with the same
  # "storageClassName" as the PVC can be bound to the PVC.
  #
  # PVCs don't necessarily have to request a class.
  # A PVC with its "storageClassName" set equal to "" is always interpreted
  # to be requesting a PV with no class so it can only be bound to
  # PVs with no class (CAN BE NO ANNOTATIONS or one set equal to "")
  #
  # HOWEVER, PVC with no "storageClassName" is not quite the same and is treated
  # differently by the cluster depending on whether the DefaultStorageClass
  # admission plugin is turned on. If default StorageClass is set
  # PVC with no "storageClassName" will use dynamic provisioning instead.
  #
  # See docs for more information. Configuration about dynamic provisioning
  # and StorageClass beyond this is out of scope for this example.
  storageClassName: manual
  resources:
    requests:
      storage: 1.5Gi
  # Kubernetes also match PV and PVC based on these access modes
  #
  # So your PV configuration need to overlap with configuration
  #
  # ReadWriteOnce means the volume can be mounted as read-write by
  # a single node.
  #
  # ReadWriteOnce access mode still can allow multiple pods to access
  # (read from or write to) that volume when the pods are running on
  # the same node.
  accessModes:
    - ReadWriteOnce
